// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA54Kzi7zWCQj3KhNPYl4YSVqy3qJUSr4o',
    appId: '1:1011670183318:web:8f07081159d67c861041b7',
    messagingSenderId: '1011670183318',
    projectId: 'kago-8f492',
    authDomain: 'kago-8f492.firebaseapp.com',
    storageBucket: 'kago-8f492.appspot.com',
    measurementId: 'G-CFY18Y2N2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTrVkjMB8kipjflmAWpmFPvNuwMBhJZ0U',
    appId: '1:1011670183318:android:6e9d1779e7187c441041b7',
    messagingSenderId: '1011670183318',
    projectId: 'kago-8f492',
    storageBucket: 'kago-8f492.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjP3yn0R4VCDCM9oUFOSloiaRcIa0o1-E',
    appId: '1:1011670183318:ios:173aa3b087171f741041b7',
    messagingSenderId: '1011670183318',
    projectId: 'kago-8f492',
    storageBucket: 'kago-8f492.appspot.com',
    iosClientId: '1011670183318-095fpkk7thphk8jte3grtersvuiv77qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kago',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjP3yn0R4VCDCM9oUFOSloiaRcIa0o1-E',
    appId: '1:1011670183318:ios:173aa3b087171f741041b7',
    messagingSenderId: '1011670183318',
    projectId: 'kago-8f492',
    storageBucket: 'kago-8f492.appspot.com',
    iosClientId: '1011670183318-095fpkk7thphk8jte3grtersvuiv77qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kago',
  );
}
